# Generated by Django 4.0.6 on 2022-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_capture_color_game_winner_move_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capture",
            name="color",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="move",
            name="color",
            field=models.BooleanField(),
        ),
    ]
