# Generated by Django 4.0.6 on 2022-07-10 17:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_capture_color_alter_move_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_id",
            field=models.CharField(
                default=uuid.uuid4, max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
